dangerouslyAllowAllBuilds: true
minimumReleaseAge: 0
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
packages:
  - .
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - '@swc/core'
trustLockfile: true
