minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true

trustLockfile: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
dangerouslyAllowAllBuilds: true
shellEmulator: true

packages:
  - .
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - '@swc/core'
