packages:
  - .
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - '@swc/core'
dangerouslyAllowAllBuilds: true
minimumReleaseAge: 0
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
trustLockfile: true
